let v = [
  "Albania",
  "Antigua & Deps",
  "Bosnia Herzegovina",
  "Brunei",
  "Burkina",
  "Cambodia",
  "Central African Rep",
  "Comoros",
  "Congo {Democratic Rep}",
  "Djibouti",
  "Guinea-Bissau",
  "Ireland {Republic}",
  "Ivory Coast",
  "Korea North",
  "Korea South",
  "Laos",
  "Lesotho",
  "Macedonia",
  "Malawi",
  "Moldova",
  "Montenegro",
  "Myanmar",
  " {Burma}",
  "Philippines",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Sao Tome & Principe",
  "Somalia",
  "South Sudan",
  "Swaziland",
  "Syria",
  "Tanzania",
  "Trinidad & Tobago",
  "Uganda",
  "Vatican City",
  "Zambia",
  "Zimbabwe",
];

console.log(v.length);
